## 1. 데이터 불러오기

In [1]:
import pandas as pd
import numpy as np

df = pd.read_excel('../excel/ingrid_liqueur_classify_final.xlsx')
df = df.drop(["Unnamed: 0"],axis=1)
df

,칵테일명,재료명,개수,단위,oz화개수,Category,재료비율,ABV,alcohol,alcohol_classification,ingrid_classification
0,Mojito,Light Rum,2.5,oz,2.500,Rum,15.782828,40.0,NaN,NaN,NaN
1,Mojito,Juice Of Lime,2.5,half oz(juice),5.000,Ingredient,31.565657,0.0,NaN,NaN,1.0
2,Mojito,Sugar,2.0,tsp,0.250,Ingredient,1.578283,0.0,NaN,NaN,NaN
3,Mojito,Mint,3.0,NaN,0.090,Ingredient,0.568182,0.0,NaN,NaN,2.0
4,Mojito,Soda Water,1.0,cup,8.000,Ingredient,50.505051,0.0,6.313131,1.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...
2288,Spice 75,Sugar,60.0,ml,1.800,Ingredient,14.201183,0.0,NaN,NaN,NaN
2289,Spice 75,Allspice,1.0,tblsp,0.375,Ingredient,2.958580,0.0,NaN,NaN,5.0
2290,Spice 75,Rum,20.0,cl,6.000,Rum,47.337278,40.0,NaN,NaN,NaN
2291,Spice 75,Lime Juice,90.0,ml,2.700,Ingredient,21.301775,0.0,NaN,NaN,1.0
2292,Spice 75,Champagne,6.0,cl,1.800,Champagne,14.201183,12.0,20.639053,2.0,NaN

## 2. EDA & Feature Engineering

In [2]:
import matplotlib.pyplot as plt
%matplotlib inline

import seaborn as sns
sns.set()

In [3]:
df['칵테일명'].count()

2293

In [4]:
cnt = 0
name = df['칵테일명'][cnt]
print(name)

Mojito

In [5]:
df.head()

,칵테일명,재료명,개수,단위,oz화개수,Category,재료비율,ABV,alcohol,alcohol_classification,ingrid_classification
0,Mojito,Light Rum,2.5,oz,2.50,Rum,15.782828,40.0,NaN,NaN,NaN
1,Mojito,Juice Of Lime,2.5,half oz(juice),5.00,Ingredient,31.565657,0.0,NaN,NaN,1.0
2,Mojito,Sugar,2.0,tsp,0.25,Ingredient,1.578283,0.0,NaN,NaN,NaN
3,Mojito,Mint,3.0,NaN,0.09,Ingredient,0.568182,0.0,NaN,NaN,2.0
4,Mojito,Soda Water,1.0,cup,8.00,Ingredient,50.505051,0.0,6.313131,1.0,6.0

In [6]:
ps = pd.DataFrame({"칵테일명":[],"0":[],"1":[],"2":[],"3":[],"4":[],"5":[]})
ps

Empty DataFrame
Columns: [칵테일명, 0, 1, 2, 3, 4, 5]
Index: []

cnt2=0
while( cnt != df['칵테일명'].count()):
    tmp0 = tmp1 = tmp2 = tmp3 = tmp4 = tmp5 = tmp6 = 0
    while (df['칵테일명'][cnt] == name):
        if(df['ingrid_classification'][cnt]==0):
            tmp0 += df['재료비율'][cnt]
        elif(df['ingrid_classification'][cnt]==1):
            tmp1 += df['재료비율'][cnt]
        elif(df['ingrid_classification'][cnt]==2):
            tmp2 += df['재료비율'][cnt]
        elif(df['ingrid_classification'][cnt]==3):
            tmp3 += df['재료비율'][cnt]
        elif(df['ingrid_classification'][cnt]==4):
            tmp4 += df['재료비율'][cnt]
        elif(df['ingrid_classification'][cnt]==5):
            tmp5 += df['재료비율'][cnt]
        ps.loc[cnt2]= [df['칵테일명'][cnt],tmp0,tmp1,tmp2,tmp3,tmp4,tmp5]
        cnt += 1
        if(cnt == df['칵테일명'].count()):
            break
    cnt2 += 1
    if(cnt == df['칵테일명'].count()):
        break
    else:
        name = df['칵테일명'][cnt]

In [7]:
cnt2=0
while( cnt != df['칵테일명'].count()):
    tmp0 = tmp1 = tmp2 = tmp3 = tmp4 = tmp5 = tmp6 = 0
    while (df['칵테일명'][cnt] == name):
        if(df['ingrid_classification'][cnt]==0):
            tmp0 = 1
        elif(df['ingrid_classification'][cnt]==1):
            tmp1 = 1
        elif(df['ingrid_classification'][cnt]==2):
            tmp2 = 1
        elif(df['ingrid_classification'][cnt]==3):
            tmp3 = 1
        elif(df['ingrid_classification'][cnt]==4):
            tmp4 = 1
        elif(df['ingrid_classification'][cnt]==5):
            tmp5 = 1
        ps.loc[cnt2]= [df['칵테일명'][cnt],tmp0,tmp1,tmp2,tmp3,tmp4,tmp5]
        cnt += 1
        if(cnt == df['칵테일명'].count()):
            break
    cnt2 += 1
    if(cnt == df['칵테일명'].count()):
        break
    else:
        name = df['칵테일명'][cnt]

In [8]:
ps

                칵테일명    0    1    2    3    4    5
0             Mojito  0.0  1.0  1.0  0.0  0.0  0.0
1      Old Fashioned  0.0  0.0  0.0  0.0  0.0  1.0
2    Long Island Tea  0.0  1.0  0.0  0.0  0.0  0.0
3            Negroni  0.0  0.0  0.0  1.0  0.0  1.0
4       Whiskey Sour  0.0  1.0  1.0  0.0  0.0  0.0
..               ...  ...  ...  ...  ...  ...  ...
587        747 Drink  0.0  1.0  1.0  0.0  0.0  0.0
588       Aquamarine  0.0  0.0  0.0  1.0  0.0  0.0
589  Banana Cream Pi  0.0  0.0  0.0  0.0  0.0  0.0
590    Amaretto fizz  0.0  1.0  0.0  1.0  0.0  0.0
591         Spice 75  0.0  1.0  0.0  0.0  0.0  1.0

[592 rows x 7 columns]

import matplotlib.pyplot as plt
%matplotlib inline

import seaborn as sns
sns.set()

#sns.pairplot(ps)
#ps = ps.T
plt.figure(figsize=(20,15))
sns.heatmap(ps.corr(), annot=True,fmt='.2f',square=True)

plt.show()

In [9]:
#ps_grouped = ps["칵테일명"].groupby(ps["1","0"])
ps_grouped = ps.groupby(["0","1","2","3","4","5"])
#for name in ps.groupby(["0","1","2","3","4","5"]):
 #   print(n)

In [10]:
ps_grouped

In [11]:
ps_grouped.describe()

                         칵테일명
                        count unique                         top freq
0   1   2   3   4   5
0.0 0.0 0.0 0.0 0.0 0.0    60     60                    Shot-gun    1
                    1.0    16     16               Old Fashioned    1
                1.0 0.0    35     35             Jamaican Coffee    1
                    1.0     6      6                 Brainteaser    1
            1.0 0.0 0.0    41     41                   Jam Donut    1
                    1.0     8      8                 Mulled Wine    1
                1.0 0.0    48     48                     Quentin    1
                    1.0     3      3                Dirty Nipple    1
        1.0 0.0 0.0 0.0    42     42               Kiss me Quick    1
                    1.0     3      3                  Moranguito    1
                1.0 0.0    11     11                 Grim Reaper    1
            1.0 0.0 0.0    11     11                 Red Snapper    1
                    1.0     3      3            Amaretto Liqueur    1
                1.0 0.0     3      3                Bruce's Puce    1
    1.0 0.0 0.0 0.0 0.0   101    101                Green Goblin    1
                    1.0    17     17           Corpse Reviver #2    1
                1.0 0.0    14     14                 Tomato Tang    1
                    1.0     1      1                        B-53    1
            1.0 0.0 0.0    35     35         Alice in Wonderland    1
                    1.0     5      5               Abbey Martini    1
                1.0 0.0     3      3                     Vesuvio    1
                    1.0     1      1         Flaming Lamborghini    1
        1.0 0.0 0.0 0.0    87     87                 Casa Blanca    1
                    1.0     7      7                      Zombie    1
                1.0 0.0     8      8           Banana Milk Shake    1
            1.0 0.0 0.0     9      9        A True Amaretto Sour    1
                    1.0     3      3          Spiced Peach Punch    1
1.0 0.0 0.0 0.0 0.0 0.0     1      1  A.D.M. (After Dinner Mint)    1
                1.0 0.0     3      3                 Iced Coffee    1
            1.0 0.0 0.0     1      1             Hot Creamy Bush    1
                1.0 0.0     2      2                   Afternoon    1
        1.0 1.0 0.0 0.0     2      2               Thai Iced Tea    1
    1.0 0.0 0.0 0.0 1.0     1      1      Kill the cold Smoothie    1
        1.0 0.0 0.0 0.0     1      1               Sweet Sangria    1

In [12]:
ps_list = list(ps_grouped)
ps_list

[((0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
                                      칵테일명    0    1    2    3    4    5
  16                        Alfie Cocktail  0.0  0.0  0.0  0.0  0.0  0.0
  27                            Angel Face  0.0  0.0  0.0  0.0  0.0  0.0
  37                         Black Russian  0.0  0.0  0.0  0.0  0.0  0.0
  72                       Flying Dutchman  0.0  0.0  0.0  0.0  0.0  0.0
  82                            Gin Cooler  0.0  0.0  0.0  0.0  0.0  0.0
  90                             Gin Toddy  0.0  0.0  0.0  0.0  0.0  0.0
  97                     Hawaiian Cocktail  0.0  0.0  0.0  0.0  0.0  0.0
  113                        Lord And Lady  0.0  0.0  0.0  0.0  0.0  0.0
  127                   Port Wine Cocktail  0.0  0.0  0.0  0.0  0.0  0.0
  131                            Queen Bee  0.0  0.0  0.0  0.0  0.0  0.0
  143                            Rum Toddy  0.0  0.0  0.0  0.0  0.0  0.0
  172                              Veteran  0.0  0.0  0.0  0.0  0.0  0.0
  175                      Vodka And Tonic  0.0  0.0  0.0  0.0  0.0  0.0
  176                  Waikiki Beachcomber  0.0  0.0  0.0  0.0  0.0  0.0
  177                           Whisky Mac  0.0  0.0  0.0  0.0  0.0  0.0
  238                          Absinthe #2  0.0  0.0  0.0  0.0  0.0  0.0
  247            Scottish Highland Liqueur  0.0  0.0  0.0  0.0  0.0  0.0
  269                   Brave Bull Shooter  0.0  0.0  0.0  0.0  0.0  0.0
  270                      Fahrenheit 5000  0.0  0.0  0.0  0.0  0.0  0.0
  286                          Black & Tan  0.0  0.0  0.0  0.0  0.0  0.0
  290                      Snake Bite (UK)  0.0  0.0  0.0  0.0  0.0  0.0
  299                             410 Gone  0.0  0.0  0.0  0.0  0.0  0.0
  303                        Apple Slammer  0.0  0.0  0.0  0.0  0.0  0.0
  306                           Jelly Bean  0.0  0.0  0.0  0.0  0.0  0.0
  312                           3 Wise Men  0.0  0.0  0.0  0.0  0.0  0.0
  313                           Miami Vice  0.0  0.0  0.0  0.0  0.0  0.0
  314                                 AT&T  0.0  0.0  0.0  0.0  0.0  0.0
  355                     Tequila Surprise  0.0  0.0  0.0  0.0  0.0  0.0
  356                           Cream Soda  0.0  0.0  0.0  0.0  0.0  0.0
  357                                 ACID  0.0  0.0  0.0  0.0  0.0  0.0
  366                               Zinger  0.0  0.0  0.0  0.0  0.0  0.0
  367                          Jello shots  0.0  0.0  0.0  0.0  0.0  0.0
  373                        Limona Corona  0.0  0.0  0.0  0.0  0.0  0.0
  383                           Zenmeister  0.0  0.0  0.0  0.0  0.0  0.0
  385                                  252  0.0  0.0  0.0  0.0  0.0  0.0
  391                        Vodka Russian  0.0  0.0  0.0  0.0  0.0  0.0
  393                     110 in the shade  0.0  0.0  0.0  0.0  0.0  0.0
  417                               Radler  0.0  0.0  0.0  0.0  0.0  0.0
  433                  Jack's Vanilla Coke  0.0  0.0  0.0  0.0  0.0  0.0
  436                            Applejack  0.0  0.0  0.0  0.0  0.0  0.0
  438                   Arizona Antifreeze  0.0  0.0  0.0  0.0  0.0  0.0
  439                      Black and Brown  0.0  0.0  0.0  0.0  0.0  0.0
  444                           Zipperhead  0.0  0.0  0.0  0.0  0.0  0.0
  450     Radioactive Long Island Iced Tea  0.0  0.0  0.0  0.0  0.0  0.0
  451                             Shot-gun  0.0  0.0  0.0  0.0  0.0  0.0
  459              Gideon's Green Dinosaur  0.0  0.0  0.0  0.0  0.0  0.0
  461                       Kool First Aid  0.0  0.0  0.0  0.0  0.0  0.0
  465                            Buccaneer  0.0  0.0  0.0  0.0  0.0  0.0
  468                Caribbean Boilermaker  0.0  0.0  0.0  0.0  0.0  0.0
  479                          Citrus Coke  0.0  0.0  0.0  0.0  0.0  0.0
  501                              Stinger  0.0  0.0  0.0  0.0  0.0  0.0
  503                              Bellini  0.0  0.0  0.0  0.0  0.0  0.0
  512                 Long Island Iced Tea  0.0  0.0  0.0  0.0  0.0  0.0
  519                      Dark and Stormy  0.0  0.0  0.0  0.0  0.0  0.0
  521                       French Martini  0.0  0.0  0.0  0.0  0.0  0.0
  526                               Vesper  0.0  0.0  0.0  0.0  0.0  0.0
  544  Empellón Cocina's Fat-Washed Mezcal  0.0  0.0  0.0  0.0  0.0  0.0
  565                   A Furlong Too Late  0.0  0.0  0.0  0.0  0.0  0.0
  576                      Tequila Slammer  0.0  0.0  0.0  0.0  0.0  0.0
  589                      Banana Cream Pi  0.0  0.0  0.0  0.0  0.0  0.0),
 ((0.0, 0.0, 0.0, 0.0, 0.0, 1.0),
                               칵테일명    0    1    2    3    4    5
  1                   Old Fashioned  0.0  0.0  0.0  0.0  0.0  1.0
  60             Champagne Cocktail  0.0  0.0  0.0  0.0  0.0  1.0
  69              Dubonnet Cocktail  0.0  0.0  0.0  0.0  0.0  1.0
  123                      Pink Gin  0.0  0.0  0.0  0.0  0.0  1.0
  140             Rum Old-fashioned  0.0  0.0  0.0  0.0  0.0  1.0
  146                       Sazerac  0.0  0.0  0.0  0.0  0.0  1.0
  206  Pineapple Gingerale Smoothie  0.0  0.0  0.0  0.0  0.0  1.0
  245               Creme de Menthe  0.0  0.0  0.0  0.0  0.0  1.0
  302           Flander's Flake-Out  0.0  0.0  0.0  0.0  0.0  1.0
  360                 Freddy Kruger  0.0  0.0  0.0  0.0  0.0  1.0
  413                       Zambeer  0.0  0.0  0.0  0.0  0.0  1.0
  419                  Campari Beer  0.0  0.0  0.0  0.0  0.0  1.0
  510                  Horse's Neck  0.0  0.0  0.0  0.0  0.0  1.0
  523                        Spritz  0.0  0.0  0.0  0.0  0.0  1.0
  577              Spritz Veneziano  0.0  0.0  0.0  0.0  0.0  1.0
  580                     Broadside  0.0  0.0  0.0  0.0  0.0  1.0),
 ((0.0, 0.0, 0.0, 0.0, 1.0, 0.0),
                                칵테일명    0    1    2    3    4    5
  20                         Almeria  0.0  0.0  0.0  0.0  1.0  0.0
  61                      Cherry Rum  0.0  0.0  0.0  0.0  1.0  0.0
  63         Chocolate Black Russian  0.0  0.0  0.0  0.0  1.0  0.0
  117                Midnight Cowboy  0.0  0.0  0.0  0.0  1.0  0.0
  135                     Royal Fizz  0.0  0.0  0.0  0.0  1.0  0.0
  178                  White Russian  0.0  0.0  0.0  0.0  1.0  0.0
  188                      Egg Cream  0.0  0.0  0.0  0.0  1.0  0.0
  194                    Lassi Khara  0.0  0.0  0.0  0.0  1.0  0.0
  212       Castillian Hot Chocolate  0.0  0.0  0.0  0.0  1.0  0.0
  214                Chocolate Drink  0.0  0.0  0.0  0.0  1.0  0.0
  216       Hot Chocolate to Die for  0.0  0.0  0.0  0.0  1.0  0.0
  218            Nuked Hot Chocolate  0.0  0.0  0.0  0.0  1.0  0.0
  229                         Frappé  0.0  0.0  0.0  0.0  1.0  0.0
  231             Iced Coffee Fillip  0.0  0.0  0.0  0.0  1.0  0.0
  233                          Melya  0.0  0.0  0.0  0.0  1.0  0.0
  242                 Coffee Liqueur  0.0  0.0  0.0  0.0  1.0  0.0
  248                      Tia-Maria  0.0  0.0  0.0  0.0  1.0  0.0
  255       Egg-Nog - Classic Cooked  0.0  0.0  0.0  0.0  1.0  0.0
  316                   Irish Coffee  0.0  0.0  0.0  0.0  1.0  0.0
  322                   Jamaica Kiss  0.0  0.0  0.0  0.0  1.0  0.0
  327                     Cafe Savoy  0.0  0.0  0.0  0.0  1.0  0.0
  329                    Mocha-Berry  0.0  0.0  0.0  0.0  1.0  0.0
  392                       Danbooka  0.0  0.0  0.0  0.0  1.0  0.0
  395                    Baby Eskimo  0.0  0.0  0.0  0.0  1.0  0.0
  409                Jamaican Coffee  0.0  0.0  0.0  0.0  1.0  0.0
  415             Black Forest Shake  0.0  0.0  0.0  0.0  1.0  0.0
  441                      Avalanche  0.0  0.0  0.0  0.0  1.0  0.0
  442  Brandon and Will's Coke Float  0.0  0.0  0.0  0.0  1.0  0.0
  446                   Kioki Coffee  0.0  0.0  0.0  0.0  1.0  0.0
  454                    Sweet Tooth  0.0  0.0  0.0  0.0  1.0  0.0
  462                  Irish Russian  0.0  0.0  0.0  0.0  1.0  0.0
  500                     Porto flip  0.0  0.0  0.0  0.0  1.0  0.0
  520               Espresso Martini  0.0  0.0  0.0  0.0  1.0  0.0
  528                    Butter Baby  0.0  0.0  0.0  0.0  1.0  0.0
  578               Espresso Rumtini  0.0  0.0  0.0  0.0  1.0  0.0),
 ((0.0, 0.0, 0.0, 0.0, 1.0, 1.0),
                   칵테일명    0    1    2    3    4    5
  227             Karsk  0.0  0.0  0.0  0.0  1.0  1.0
  235       Thai Coffee  0.0  0.0  0.0  0.0  1.0  1.0
  236  Thai Iced Coffee  0.0  0.0  0.0  0.0  1.0  1.0
  292       Brainteaser  0.0  0.0  0.0  0.0  1.0  1.0
  397    Swedish Coffee  0.0  0.0  0.0  0.0  1.0  1.0
  575   Slippery Nipple  0.0  0.0  0.0  0.0  1.0  1.0),
 ((0.0, 0.0, 0.0, 1.0, 0.0, 0.0),
                                       칵테일명    0    1    2    3    4    5
  25                       Amaretto Stinger  0.0  0.0  0.0  1.0  0.0  0.0
  31                          Arise My Love  0.0  0.0  0.0  1.0  0.0  0.0
  45                   Bobby Burns Cocktail  0.0  0.0  0.0  1.0  0.0  0.0
  70                       English Highball  0.0  0.0  0.0  1.0  0.0  0.0
  80                       Gentleman's Club  0.0  0.0  0.0  1.0  0.0  0.0
  92                              Godfather  0.0  0.0  0.0  1.0  0.0  0.0
  93                              Godmother  0.0  0.0  0.0  1.0  0.0  0.0
  103                     Jewel Of The Nile  0.0  0.0  0.0  1.0  0.0  0.0
  106                      Kentucky B And B  0.0  0.0  0.0  1.0  0.0  0.0
  107                      Kentucky Colonel  0.0  0.0  0.0  1.0  0.0  0.0
  111                    Lone Tree Cocktail  0.0  0.0  0.0  1.0  0.0  0.0
  125                        Poppy Cocktail  0.0  0.0  0.0  1.0  0.0  0.0
  144                            Rusty Nail  0.0  0.0  0.0  1.0  0.0  0.0
  158                          Sol Y Sombra  0.0  0.0  0.0  1.0  0.0  0.0
  173                                Victor  0.0  0.0  0.0  1.0  0.0  0.0
  277                      Damned if you do  0.0  0.0  0.0  1.0  0.0  0.0
  281                    Flaming Dr. Pepper  0.0  0.0  0.0  1.0  0.0  0.0
  291                            Bob Marley  0.0  0.0  0.0  1.0  0.0  0.0
  296                                   ABC  0.0  0.0  0.0  1.0  0.0  0.0
  304                         Amaretto Sour  0.0  0.0  0.0  1.0  0.0  0.0
  309                            Kir Royale  0.0  0.0  0.0  1.0  0.0  0.0
  310                            Jackhammer  0.0  0.0  0.0  1.0  0.0  0.0
  317  '57 Chevy with a White License Plate  0.0  0.0  0.0  1.0  0.0  0.0
  369                            Turkeyball  0.0  0.0  0.0  1.0  0.0  0.0
  376                     Texas Rattlesnake  0.0  0.0  0.0  1.0  0.0  0.0
  408                          Herbal flame  0.0  0.0  0.0  1.0  0.0  0.0
  416                                    GG  0.0  0.0  0.0  1.0  0.0  0.0
  428                 Amaretto Sweet & Sour  0.0  0.0  0.0  1.0  0.0  0.0
  440                        A Piece of Ass  0.0  0.0  0.0  1.0  0.0  0.0
  448                             Zorbatini  0.0  0.0  0.0  1.0  0.0  0.0
  463                     Auburn Headbanger  0.0  0.0  0.0  1.0  0.0  0.0
  467                         24k nightmare  0.0  0.0  0.0  1.0  0.0  0.0
  478                           Royal Bitch  0.0  0.0  0.0  1.0  0.0  0.0
  482                       Amaretto Sunset  0.0  0.0  0.0  1.0  0.0  0.0
  487                             Jam Donut  0.0  0.0  0.0  1.0  0.0  0.0
  506                     French Connection  0.0  0.0  0.0  1.0  0.0  0.0
  511                                   Kir  0.0  0.0  0.0  1.0  0.0  0.0
  536                               Addison  0.0  0.0  0.0  1.0  0.0  0.0
  546                        French Negroni  0.0  0.0  0.0  1.0  0.0  0.0
  562                             Tipperary  0.0  0.0  0.0  1.0  0.0  0.0
  588                            Aquamarine  0.0  0.0  0.0  1.0  0.0  0.0),
 ((0.0, 0.0, 0.0, 1.0, 0.0, 1.0),
                   칵테일명    0    1    2    3    4    5
  3             Negroni  0.0  0.0  0.0  1.0  0.0  1.0
  33          Artillery  0.0  0.0  0.0  1.0  0.0  1.0
  73   Flying Scotchman  0.0  0.0  0.0  1.0  0.0  1.0
  240  Angelica Liqueur  0.0  0.0  0.0  1.0  0.0  1.0
  257         Gluehwein  0.0  0.0  0.0  1.0  0.0  1.0
  259       Mulled Wine  0.0  0.0  0.0  1.0  0.0  1.0
  387             Zorro  0.0  0.0  0.0  1.0  0.0  1.0
  549      Boulevardier  0.0  0.0  0.0  1.0  0.0  1.0),
 ((0.0, 0.0, 0.0, 1.0, 1.0, 0.0),
                               칵테일명    0    1    2    3    4    5
  14                      Alexander  0.0  0.0  0.0  1.0  1.0  0.0
  15               Brandy Alexander  0.0  0.0  0.0  1.0  1.0  0.0
  21                     Almond Joy  0.0  0.0  0.0  1.0  1.0  0.0
  22             Amaretto And Cream  0.0  0.0  0.0  1.0  1.0  0.0
  54                    Brandy Flip  0.0  0.0  0.0  1.0  1.0  0.0
  74                      Foxy Lady  0.0  0.0  0.0  1.0  1.0  0.0
  91                       Godchild  0.0  0.0  0.0  1.0  1.0  0.0
  122                        Orgasm  0.0  0.0  0.0  1.0  1.0  0.0
  128                Port Wine Flip  0.0  0.0  0.0  1.0  1.0  0.0
  134                       Quentin  0.0  0.0  0.0  1.0  1.0  0.0
  139                Rum Milk Punch  0.0  0.0  0.0  1.0  1.0  0.0
  147                       Scooter  0.0  0.0  0.0  1.0  1.0  0.0
  152                 Sherry Eggnog  0.0  0.0  0.0  1.0  1.0  0.0
  153                   Sherry Flip  0.0  0.0  0.0  1.0  1.0  0.0
  213            Chocolate Beverage  0.0  0.0  0.0  1.0  1.0  0.0
  215            Drinking Chocolate  0.0  0.0  0.0  1.0  1.0  0.0
  219  Orange Scented Hot Chocolate  0.0  0.0  0.0  1.0  1.0  0.0
  220             Spanish chocolate  0.0  0.0  0.0  1.0  1.0  0.0
  226                  Grizzly Bear  0.0  0.0  0.0  1.0  1.0  0.0
  234                Spiking coffee  0.0  0.0  0.0  1.0  1.0  0.0
  243                  Coffee-Vodka  0.0  0.0  0.0  1.0  1.0  0.0
  254                    Egg Nog #4  0.0  0.0  0.0  1.0  1.0  0.0
  256             Egg Nog - Healthy  0.0  0.0  0.0  1.0  1.0  0.0
  279                    Quick F**K  0.0  0.0  0.0  1.0  1.0  0.0
  285                       Big Red  0.0  0.0  0.0  1.0  1.0  0.0
  287                Chocolate Milk  0.0  0.0  0.0  1.0  1.0  0.0
  295                 Oreo Mudslide  0.0  0.0  0.0  1.0  1.0  0.0
  301              Screaming Orgasm  0.0  0.0  0.0  1.0  1.0  0.0
  307                    After Five  0.0  0.0  0.0  1.0  1.0  0.0
  308                 Midnight Manx  0.0  0.0  0.0  1.0  1.0  0.0
  311                Nutty Irishman  0.0  0.0  0.0  1.0  1.0  0.0
  318                 Mother's Milk  0.0  0.0  0.0  1.0  1.0  0.0
  330                           747  0.0  0.0  0.0  1.0  1.0  0.0
  332          California Root Beer  0.0  0.0  0.0  1.0  1.0  0.0
  334                 Blind Russian  0.0  0.0  0.0  1.0  1.0  0.0
  345          Bailey's Dream Shake  0.0  0.0  0.0  1.0  1.0  0.0
  364                 Midnight Mint  0.0  0.0  0.0  1.0  1.0  0.0
  379                Amaretto Shake  0.0  0.0  0.0  1.0  1.0  0.0
  396                  Tennesee Mud  0.0  0.0  0.0  1.0  1.0  0.0
  401                   Texas Sling  0.0  0.0  0.0  1.0  1.0  0.0
  412                          B-52  0.0  0.0  0.0  1.0  1.0  0.0
  420       Almond Chocolate Coffee  0.0  0.0  0.0  1.0  1.0  0.0
  430                          H.D.  0.0  0.0  0.0  1.0  1.0  0.0
  471                 Baby Guinness  0.0  0.0  0.0  1.0  1.0  0.0
  508                   Grasshopper  0.0  0.0  0.0  1.0  1.0  0.0
  529      Boozy Snickers Milkshake  0.0  0.0  0.0  1.0  1.0  0.0
  539         Salted Toffee Martini  0.0  0.0  0.0  1.0  1.0  0.0
  555                Oatmeal Cookie  0.0  0.0  0.0  1.0  1.0  0.0),
 ((0.0, 0.0, 0.0, 1.0, 1.0, 1.0),
                칵테일명    0    1    2    3    4    5
  232    Masala Chai  0.0  0.0  0.0  1.0  1.0  1.0
  343   Dirty Nipple  0.0  0.0  0.0  1.0  1.0  1.0
  346  Bumble Bee #1  0.0  0.0  0.0  1.0  1.0  1.0),
 ((0.0, 0.0, 1.0, 0.0, 0.0, 0.0),
                                        칵테일명    0    1    2    3    4    5
  88                              Gin Squirt  0.0  0.0  1.0  0.0  0.0  0.0
  94                             Grass Skirt  0.0  0.0  1.0  0.0  0.0  0.0
  145                              Salty Dog  0.0  0.0  1.0  0.0  0.0  0.0
  156                        Singapore Sling  0.0  0.0  1.0  0.0  0.0  0.0
  181                           Apple Karate  0.0  0.0  1.0  0.0  0.0  0.0
  187  Banana Strawberry Shake Daiquiri-type  0.0  0.0  1.0  0.0  0.0  0.0
  201             Banana Cantaloupe Smoothie  0.0  0.0  1.0  0.0  0.0  0.0
  202                   Apple Berry Smoothie  0.0  0.0  1.0  0.0  0.0  0.0
  204                   Kiwi Papaya Smoothie  0.0  0.0  1.0  0.0  0.0  0.0
  208                     Strawberry Shivers  0.0  0.0  1.0  0.0  0.0  0.0
  222                       Sex on the Beach  0.0  0.0  1.0  0.0  0.0  0.0
  244                      Cranberry Cordial  0.0  0.0  1.0  0.0  0.0  0.0
  273                                 Diesel  0.0  0.0  1.0  0.0  0.0  0.0
  289                             Sea breeze  0.0  0.0  1.0  0.0  0.0  0.0
  293                           Atlantic Sun  0.0  0.0  1.0  0.0  0.0  0.0
  335                            Absolut Sex  0.0  0.0  1.0  0.0  0.0  0.0
  341                       Kool-Aid Slammer  0.0  0.0  1.0  0.0  0.0  0.0
  342                             Kurant Tea  0.0  0.0  1.0  0.0  0.0  0.0
  348                       A Splash of Nash  0.0  0.0  1.0  0.0  0.0  0.0
  370             Absolutely Cranberry Smash  0.0  0.0  1.0  0.0  0.0  0.0
  371                          Kiss me Quick  0.0  0.0  1.0  0.0  0.0  0.0
  372                            Royal Flush  0.0  0.0  1.0  0.0  0.0  0.0
  381                         Malibu Twister  0.0  0.0  1.0  0.0  0.0  0.0
  399                      Absolut Stress #2  0.0  0.0  1.0  0.0  0.0  0.0
  402                 A midsummernight dream  0.0  0.0  1.0  0.0  0.0  0.0
  406                    Snakebite and Black  0.0  0.0  1.0  0.0  0.0  0.0
  425                        Bellini Martini  0.0  0.0  1.0  0.0  0.0  0.0
  434                           Apple Grande  0.0  0.0  1.0  0.0  0.0  0.0
  437                              Adam Bomb  0.0  0.0  1.0  0.0  0.0  0.0
  455                              Downshift  0.0  0.0  1.0  0.0  0.0  0.0
  458                          Bruised Heart  0.0  0.0  1.0  0.0  0.0  0.0
  475                           Ruby Tuesday  0.0  0.0  1.0  0.0  0.0  0.0
  476                       Arctic Mouthwash  0.0  0.0  1.0  0.0  0.0  0.0
  483               Cherry Electric Lemonade  0.0  0.0  1.0  0.0  0.0  0.0
  495                                  Derby  0.0  0.0  1.0  0.0  0.0  0.0
  496                          Mary Pickford  0.0  0.0  1.0  0.0  0.0  0.0
  514                             Mint Julep  0.0  0.0  1.0  0.0  0.0  0.0
  515                            Pina Colada  0.0  0.0  1.0  0.0  0.0  0.0
  532                    Absolutely Fabulous  0.0  0.0  1.0  0.0  0.0  0.0
  550                              Greyhound  0.0  0.0  1.0  0.0  0.0  0.0
  551                                 Paloma  0.0  0.0  1.0  0.0  0.0  0.0
  567                                  A. J.  0.0  0.0  1.0  0.0  0.0  0.0),
 ((0.0, 0.0, 1.0, 0.0, 0.0, 1.0),
                  칵테일명    0    1    2    3    4    5
  119    Monkey Wrench  0.0  0.0  1.0  0.0  0.0  1.0
  427       Moranguito  0.0  0.0  1.0  0.0  0.0  1.0
  582  Halloween Punch  0.0  0.0  1.0  0.0  0.0  1.0),
 ((0.0, 0.0, 1.0, 0.0, 1.0, 0.0),
                               칵테일명    0    1    2    3    4    5
  124                     Pink Lady  0.0  0.0  1.0  0.0  1.0  0.0
  186       Banana Strawberry Shake  0.0  0.0  1.0  0.0  1.0  0.0
  190               Fruit Flip-Flop  0.0  0.0  1.0  0.0  1.0  0.0
  192               Just a Moonmint  0.0  0.0  1.0  0.0  1.0  0.0
  193  Lassi - A South Indian Drink  0.0  0.0  1.0  0.0  1.0  0.0
  197                 Lassi - Mango  0.0  0.0  1.0  0.0  1.0  0.0
  209                 Sweet Bananas  0.0  0.0  1.0  0.0  1.0  0.0
  211                Yoghurt Cooler  0.0  0.0  1.0  0.0  1.0  0.0
  359                   Grim Reaper  0.0  0.0  1.0  0.0  1.0  0.0
  404                 Fuzzy Asshole  0.0  0.0  1.0  0.0  1.0  0.0

In [13]:
ps_list[2][1]["칵테일명"]

20                           Almeria
61                        Cherry Rum
63           Chocolate Black Russian
117                  Midnight Cowboy
135                       Royal Fizz
178                    White Russian
188                        Egg Cream
194                      Lassi Khara
212         Castillian Hot Chocolate
214                  Chocolate Drink
216         Hot Chocolate to Die for
218              Nuked Hot Chocolate
229                           Frappé
231               Iced Coffee Fillip
233                            Melya
242                   Coffee Liqueur
248                        Tia-Maria
255         Egg-Nog - Classic Cooked
316                     Irish Coffee
322                     Jamaica Kiss
327                       Cafe Savoy
329                      Mocha-Berry
392                         Danbooka
395                      Baby Eskimo
409                  Jamaican Coffee
415               Black Forest Shake
441                        Avalanche
442    Brandon and Will's Coke Float
446                     Kioki Coffee
454                      Sweet Tooth
462                    Irish Russian
500                       Porto flip
520                 Espresso Martini
528                      Butter Baby
578                 Espresso Rumtini
Name: 칵테일명, dtype: object

In [14]:
rank = pd.read_excel('../excel/rank.xlsx')
rank.head()

          칵테일명          검색량
0         AT&T  25270000000
1  Black & Tan  13330000000
2   Adam & Eve   1550000000
3  Ice Pick #1    323000000
4         Rose    140000000

In [15]:
df

,칵테일명,재료명,개수,단위,oz화개수,Category,재료비율,ABV,alcohol,alcohol_classification,ingrid_classification
0,Mojito,Light Rum,2.5,oz,2.500,Rum,15.782828,40.0,NaN,NaN,NaN
1,Mojito,Juice Of Lime,2.5,half oz(juice),5.000,Ingredient,31.565657,0.0,NaN,NaN,1.0
2,Mojito,Sugar,2.0,tsp,0.250,Ingredient,1.578283,0.0,NaN,NaN,NaN
3,Mojito,Mint,3.0,NaN,0.090,Ingredient,0.568182,0.0,NaN,NaN,2.0
4,Mojito,Soda Water,1.0,cup,8.000,Ingredient,50.505051,0.0,6.313131,1.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...
2288,Spice 75,Sugar,60.0,ml,1.800,Ingredient,14.201183,0.0,NaN,NaN,NaN
2289,Spice 75,Allspice,1.0,tblsp,0.375,Ingredient,2.958580,0.0,NaN,NaN,5.0
2290,Spice 75,Rum,20.0,cl,6.000,Rum,47.337278,40.0,NaN,NaN,NaN
2291,Spice 75,Lime Juice,90.0,ml,2.700,Ingredient,21.301775,0.0,NaN,NaN,1.0
2292,Spice 75,Champagne,6.0,cl,1.800,Champagne,14.201183,12.0,20.639053,2.0,NaN

In [16]:
cnt = 0
while(cnt!=df['칵테일명'].count()):
    if df['칵테일명'][cnt]=="Mojito":
        while(df['칵테일명'][cnt]=="Mojito"):
            cnt+=1
        print(cnt-1, df['alcohol_classification'][cnt-1])
    cnt += 1

4 1.0

In [17]:
for i in rank["칵테일명"]:
    for j in ps_list[0][1]["칵테일명"]:
        if i == j:
            cnt = 0
            while(cnt!=df['칵테일명'].count()):
                if df['칵테일명'][cnt]==i:
                    while(df['칵테일명'][cnt]==i):
                        cnt+=1
                    if(df['alcohol_classification'][cnt-1]==1):
                        print(i,"도수:",int(df['alcohol'][cnt-1]))
                cnt += 1

AT&T 도수: 13
Vodka Russian 도수: 8
Bellini 도수: 13
Vodka And Tonic 도수: 8
Jello shots 도수: 11
110 in the shade 도수: 7
Applejack 도수: 14
Gin Cooler 도수: 7
Apple Slammer 도수: 10
Zinger 도수: 10
Citrus Coke 도수: 13
Caribbean Boilermaker 도수: 9
Limona Corona 도수: 6
Gideon's Green Dinosaur 도수: 8
Zipperhead 도수: 13

# 3. 구현

## (1) 좋아하는 칵테일 맛 입력받기

In [ ]:
print("다음 중 좋아하는 칵테일 맛의 번호를 차례로 입력하세요       ex) 0,1")
print("hot: 0 / 리프레싱: 1 / 프루트: 2 / 스위트: 3 / 스무디: 4 / 드라이 : 5")

taste = input("좋아하는 맛: ")

다음 중 좋아하는 칵테일 맛의 번호를 차례로 입력하세요       ex) 0,1
hot: 0 / 리프레싱: 1 / 프루트: 2 / 스위트: 3 / 스무디: 4 / 드라이 : 5

In [ ]:
print("어느 정도의 도수를 선호하시나요? 0~6단계 중 하나를 선택해주세요")
print("(0: 도수가 매우 낮음 , 4: 도수가 매우 높음)")

alcohol = input("원하는 도수: ")
alcohol = int(alcohol)

In [ ]:
# 나중에 시도해볼 예정
print("탄산이 들어간 칵테일을 원하시나요? (0: 아니요, 1: 네)")

carbonated = input("탄산 여부 : ")

## (2) 적합한 칵테일 선별하기

In [ ]:
taste_real = taste.split(',')
taste_real

for i in taste_real:
    print(i)

In [ ]:
personal_data = [0.0,0.0,0.0,0.0,0.0,0.0]

for i in taste_real:
    i = int(i)
    personal_data[i] = 1.0

personal_data = tuple(personal_data)
personal_data

In [ ]:
for i in ps_list:
    if i[0]==personal_data:
        recom1 = i[1]["칵테일명"]
    
recom1


## (3) 검색 순위와 비교해 최종 추천 칵테일 출력하기

In [ ]:
for i in rank["칵테일명"]:
    for j in recom1:
        if i == j:
            cnt = 0
            while(cnt!=df['칵테일명'].count()):
                if df['칵테일명'][cnt]==i:
                    while(df['칵테일명'][cnt]==i):
                        cnt+=1
                    if(df['alcohol_classification'][cnt-1]==alcohol):
                        print(i,"도수:",int(df['alcohol'][cnt-1]))
                cnt += 1