## 1. 데이터 불러오기

In [1]:
import pandas as pd
import numpy as np

df = pd.read_excel('./cocktail_data_categorized_ingredient_Ver.3.xlsx')
df

,Unnamed: 0,칵테일명,재료명,개수,단위,oz화개수,Category
0,0,Mojito,Light Rum,2.5,oz,2.500,Rum
1,1,Mojito,Juice Of Lime,2.5,half oz(juice),5.000,Ingredient
2,2,Mojito,Sugar,2.0,tsp,0.250,Ingredient
3,3,Mojito,Mint,3.0,NaN,0.090,Ingredient
4,4,Mojito,Soda Water,1.0,cup,8.000,Ingredient
...,...,...,...,...,...,...,...
2288,2288,Spice 75,Sugar,60.0,ml,1.800,Ingredient
2289,2289,Spice 75,Allspice,1.0,tblsp,0.375,Ingredient
2290,2290,Spice 75,Rum,20.0,cl,6.000,Rum
2291,2291,Spice 75,Lime Juice,90.0,ml,2.700,Ingredient
2292,2292,Spice 75,Champagne,6.0,cl,1.800,Champagne

## 2. EDA & Feature Engineering

In [2]:
import matplotlib.pyplot as plt
%matplotlib inline

import seaborn as sns
sns.set()

In [3]:
grouped = df["oz화개수"].groupby(df["칵테일명"])
grouped

In [4]:
grouped.describe()

,count,mean,std,min,25%,50%,75%,max
칵테일명,,,,,,,,
'57 Chevy with a White License Plate,2.0,1.000000,0.000000,1.00000,1.000,1.000,1.0000,1.00
1-900-FUK-MEUP,8.0,0.312500,0.115728,0.25000,0.250,0.250,0.3125,0.50
110 in the shade,2.0,8.750000,10.253048,1.50000,5.125,8.750,12.3750,16.00
151 Florida Bushwacker,8.0,1.937500,2.583429,0.50000,0.500,1.000,1.5000,8.00
155 Belmont,4.0,4.375000,1.750000,3.50000,3.500,3.500,4.3750,7.00
...,...,...,...,...,...,...,...,...
Zizi Coin-coin,4.0,1.710000,1.934011,0.24000,0.510,1.050,2.2500,4.50
Zoksel,7.0,5.071429,2.921594,1.00000,3.000,4.500,8.0000,8.00
Zombie,7.0,0.625953,0.683642,0.00667,0.125,0.125,1.2500,1.50
Zorbatini,2.0,0.750000,0.707107,0.25000,0.500,0.750,1.0000,1.25
Zorro,3.0,0.600000,0.000000,0.60000,0.600,0.600,0.6000,0.60

In [5]:
df['칵테일명'].count()

2293

In [22]:
cnt = 0
name = df['칵테일명'][cnt]
print(name)

Mojito

In [23]:
cnt2 = 0 
while( cnt != df['칵테일명'].count()):
    sum = 0
    while (df['칵테일명'][cnt] == name):
        sum += df['oz화개수'][cnt]
        cnt += 1 
        if(cnt == df['칵테일명'].count()):
            break
    print(name+":"+str(sum))
    for cnt2 in range(cnt2,cnt,1):
        df['재료비율'][cnt2] = df['oz화개수'][cnt2]/sum*100
        #print(sum)
    cnt2=cnt
    if(cnt == df['칵테일명'].count()):
        break
    else:
        name = df['칵테일명'][cnt]

Mojito:15.84
Old Fashioned:1.5037500000000001
Long Island Tea:3.03125
Negroni:3.0
Whiskey Sour:3.5124999999999997
Dry Martini:2.15
Daiquiri:2.625
Margarita:3.06
Manhattan:3.659375
Moscow Mule:12.0
After Dinner Cocktail:8.5
After Supper Cocktail:2.0625
Alabama Slammer:2.53125
Alaska Cocktail:2.3125
Alexander:3.35
Brandy Alexander:3.35
Alfie Cocktail:1.90625
Algonquin:3.5
Allegheny:2.375
Allies Cocktail:2.0625
Almeria:3.9
Almond Joy:3.0
Amaretto And Cream:3.0
Amaretto Mist:6.0
Amaretto Rose:10.0
Amaretto Stinger:2.25
Amaretto Tea:9.7
Angel Face:2.0
Applecar:3.0
Apricot Lady:8.525
Archbishop:7.625
Arise My Love:1.125
Arthur Tompkins:2.75
Artillery:1.75
Balmoral:2.5625
Banana Daiquiri:7.8
Bermuda Highball:10.25
Black Russian:2.25
Blackthorn:2.5
Bloody Maria:3.39375
Bloody Mary:4.910425
Blue Lagoon:10.3
Blue Margarita:3.56
Blue Mountain:3.625
Bluebird:2.8625
Bobby Burns Cocktail:3.15625
Boomerang:2.925

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()

Boston Sidecar:3.25
Boston Sour:4.625
Classic Old-Fashioned:8.078750000000001
Bourbon Sling:3.375
Bourbon Sour:7.8625
Boxcar:3.5875
Brandy Cobbler:14.425
Brandy Flip:4.14
Brandy Sour:3.5124999999999997
Caipirinha:7.25
California Lemonade:18.40625
Casa Blanca:2.5625
Casino Royale:3.25625
Champagne Cocktail:1.15375
Cherry Rum:1.8125
Chicago Fizz:12.025
Chocolate Black Russian:6.5
City Slicker:2.875
Clove Cocktail:2.0
Cuba Libre:6.0
Dragonfly:10.0
Dry Rob Roy:2.6875
Dubonnet Cocktail:2.28125
English Highball:10.25
English Rose Cocktail:3.45625
Flying Dutchman:2.5
Flying Scotchman:2.0625
Foxy Lady:3.0
French "75":12.05
Frisco Sour:4.6
Frozen Daiquiri:11.8
Frozen Mint Daiquiri:2.68
Frozen Pineapple Daiquiri:21.9375
Gentleman's Club:4.5
Gin And Tonic:11.5
Gin Cooler:10.06
Gin Daisy:7.925
Gin Fizz:11.125
Gin Sling:3.25
Gin Smash:3.78
Gin Sour:7.8625
Gin Squirt:25.72
Gin Swizzle:6.65625
Gin Toddy:2.3125
Godchild:3.0
Godfather:2.25
Godmother:2.25
Grass Skirt:4.0625
Harvey Wallbanger:5.5
Havana Cocktail:2.125
Hawaiian Cocktail:2.875
Highland Fling Cocktail:2.4625
Imperial Fizz:11.125
Irish Spring:4.1
Jack Rose Cocktail:2.625
Japanese Fizz:11.9
Jewel Of The Nile:2.5
John Collins:10.925
Kamikaze:3.0
Kentucky B And B:2.5
Kentucky Colonel:3.5
Lady Love Fizz:12.275
Loch Lomond:3.0
London Town:2.0625
Lone Tree Cocktail:2.25
Lone Tree Cooler:10.06
Lord And Lady:2.0
Mai Tai:3.8
Martinez Cocktail:2.3625
Martini:2.15
Midnight Cowboy:3.5
Mississippi Planters Punch:11.375
Monkey Wrench:4.53125
New York Sour:8.925
Orange Oasis:7.0
Orgasm:3.0
Pink Gin:2.09375
Pink Lady:2.65
Poppy Cocktail:2.25
Port And Starboard:0.875
Port Wine Cocktail:2.5625
Port Wine Flip:3.725
Quaker's Cocktail:2.25
Quarter Deck Cocktail:2.83
Queen Bee:3.0
Queen Charlotte:3.3
Queen Elizabeth:2.1875
Quentin:3.015
Royal Fizz:7.5
Royal Gin Fizz:12.625
Rum Cobbler:14.425
Rum Cooler:10.5
Rum Milk Punch:10.475
Rum Old-fashioned:1.84375
Rum Screwdriver:6.5
Rum Sour:7.8625
Rum Toddy:2.5
Rusty Nail:2.0
Salty Dog:6.53125
Sazerac:2.375
Scooter:3.0
Scotch Cobbler:2.5799999999999996
Scotch Sour:3.0124999999999997
Screwdriver:5.0
Shanghai Cocktail:1.6875
Sherry Eggnog:6.975
Sherry Flip:3.725
Sidecar:3.5
Sidecar Cocktail:2.0
Singapore Sling:12.3
Sloe Gin Cocktail:2.0625
Sol Y Sombra:3.0
Stone Sour:3.0
Strawberry Daiquiri:3.625
Strawberry Margarita:4.06
Tequila Fizz:5.025
Tequila Sour:3.5749999999999997
Thriller:3.5
Tom Collins:10.925
Turf Cocktail:2.09375
Tuxedo Cocktail:3.425
Valencia Cocktail:1.9375
Van Vleet:5.0
Vermouth Cassis:10.25
Vesuvio:3.525
Veteran:2.5
Victor:2.5
Victory Collins:7.925
Vodka And Tonic:10.0
Waikiki Beachcomber:1.875
Whisky Mac:2.5
White Russian:4.7
Afterglow:9.0
Alice Cocktail:2.4
Apple Karate:22.0
Bora Bora:5.3999999999999995
Orangeade:14.75
Rail Splitter:4.25
Banana Milk Shake:6.45
Banana Strawberry Shake:27.875
Banana Strawberry Shake Daiquiri-type:27.5
Egg Cream:12.75
Fruit Cooler:54.49
Fruit Flip-Flop:16.0
Fruit Shake:17.470000000000002
Just a Moonmint:16.75
Lassi - A South Indian Drink:14.125
Lassi Khara:24.135
Lassi Raita:21.819999999999997
Lassi - Sweet:26.31
Lassi - Mango:38.0
Lemouroudji:151.15
Limeade:10.375
Imperial Cocktail:3.0
Banana Cantaloupe Smoothie:5.0
Apple Berry Smoothie:9.0
Grape lemon pineapple Smoothie:11.625
Kiwi Papaya Smoothie:10.3
Mango Orange Smoothie:14.0
Pineapple Gingerale Smoothie:2.5075
Kill the cold Smoothie:9.155
Strawberry Shivers:16.5
Sweet Bananas:20.375
Tomato Tang:16.59375
Yoghurt Cooler:16.24
Castillian Hot Chocolate:48.875
Chocolate Beverage:55.625
Chocolate Drink:36.5
Drinking Chocolate:12.77
Hot Chocolate to Die for:20.3875
Microwave Hot Cocoa:20.1875
Nuked Hot Chocolate:12.4375
Orange Scented Hot Chocolate:20.0775
Spanish chocolate:18.6625
Lemon Shot:2.3600000000000003
Sex on the Beach:5.05
Autodafé:9.23125
Gagliardo:10.0
Surf City Lifesaver:4.5
Grizzly Bear:5.5
Karsk:3.0
Happy Skipper:6.19
Frappé:8.1875
Iced Coffee:38.0
Iced Coffee Fillip:3.25
Masala Chai:27.6925
Melya:1.25
Spiking coffee:3.06
Thai Coffee:13.28125
Thai Iced Coffee:4.0600000000000005
Thai Iced Tea:6.5200000000000005
Absinthe #2:28.405
Amaretto Liqueur:32.51087
Angelica Liqueur:20.22334
Caribbean Orange Liqueur:48.14
Coffee Liqueur:77.25
Coffee-Vodka:49.075
Cranberry Cordial:57.75
Creme de Menthe:129.375
Irish Cream:25.89501
Scottish Highland Liqueur:37.88125
Tia-Maria:24.04
Aloha Fruit punch:70.8125
Apple Cider Punch #1:148.66500000000002
Artillery Punch:139.1
Berry Deadly:249.0
Cranberry Punch:140.375
Egg Nog #4:45.50625
Egg-Nog - Classic Cooked:43.15625
Egg Nog - Healthy:24.725
Gluehwein:38.7
Holloween Punch:6.300000000000001
Mulled Wine:56.98
Sangria #1:45.09
Sweet Sangria:95.1
Sangria - The World's Best:78.5
Spiced Peach Punch:70.9925
Strawberry Lemonade:15.615
Sunny Holiday Punch:125.5
Wine Cooler:7.24
Wine Punch:63.5
Bruce's Puce:3.7
Brave Bull Shooter:1.0
Fahrenheit 5000:1.03125
Popped cherry:12.0
Atomic Lokade:7.3
Diesel:16.03125
Afternoon:5.0
Kool-Aid Shot:14.3
National Aquarium:4.03125
Damned if you do:1.0
Long vodka:8.135
Quick F**K:3.0
Owen's Grandmother's Revenge:44.0
Flaming Dr. Pepper:5.0
New York Lemonade:6.0
Caipirissima:12.49
Pisco Sour:3.8025
Big Red:1.0
Black & Tan:2.0
Chocolate Milk:3.53125
B-53:3.465
Sea breeze:6.5
Snake Bite (UK):16.0
Bob Marley:1.5
Brainteaser:1.9499999999999997
Atlantic Sun:3.6312499999999996
Green Goblin:19.5
Oreo Mudslide:5.4
ABC:0.99
Pink Panty Pulldowns:65.0
Ice Pick #1:10.5
410 Gone:5.5
Tequila Sunrise:8.0
Screaming Orgasm:3.0
Flander's Flake-Out:34.0
Apple Slammer:2.0
Amaretto Sour:4.5
Cuba Libra:14.69
Jelly Bean:2.0
After Five:2.73
Midnight Manx:6.03125
Kir Royale:6.0
Jackhammer:2.0
Nutty Irishman:3.0
3 Wise Men:0.99
Miami Vice:7.0
AT&T:6.0
69 Special:6.75
Irish Coffee:10.0
'57 Chevy with a White License Plate:2.0
Mother's Milk:3.0
Zippy's Revenge:8.0
Belgian Blue:9.2
Red Snapper:10.5
Jamaica Kiss:10.24
Absolut Summertime:6.05
Cosmopolitan Martini:2.53125
Ziemes Martini Apfelsaft:6.0
Vodka Martini:2.4
Cafe Savoy:5.0
Snowball:11.040000000000001
Mocha-Berry:10.45
747:0.99
Addison Special:11.875
California Root Beer:9.5
Amaretto Stone Sour:3.0
Blind Russian:10.75
Absolut Sex:2.53125
Aztec Punch:44.5
Lemon Drop:13.5
Absolut limousine:10.395
Absolut Evergreen:5.74
Lunch Box:23.25
Kool-Aid Slammer:1.0
Kurant Tea:9.26
Dirty Nipple:3.7
Darkwood Sling:3.24
Bailey's Dream Shake:5.7
Bumble Bee #1:0.99
A.D.M. (After Dinner Mint):9.75
A Splash of Nash:5.0
Amaretto Sunrise:4.375
Arizona Stingers:19.0
Orange Push-up:6.03125
151 Florida Bushwacker:15.5
Zizi Coin-coin:6.84
50/50:10.53125
Tequila Surprise:34.05336
Cream Soda:2.0
ACID:2.0
Arctic Fish:1.26125
Grim Reaper:2.03125
Freddy Kruger:1.5
Bubble Gum:2.7
Kiwi Lemon:3.24
Hot Creamy Bush:12.125
Midnight Mint:2.5
Talos Coffee:4.0
Zinger:28.0
Jello shots:58.0
Rum Punch:23.54
Turkeyball:1.78125
Absolutely Cranberry Smash:8.24
Kiss me Quick:6.54
Royal Flush:4.0
Limona Corona:26.0
Pysch Vitamin Light:3.24
Apello:2.6999999999999993
Texas Rattlesnake:2.53125
After sex:3.9
San Francisco:5.2
Amaretto Shake:6.0
A Day at the Beach:6.0
Malibu Twister:5.0
Space Odyssey:14.8
Zenmeister:1.0
Avalon:19.5
252:3.5
3-Mile Long Island Iced Tea:11.046875
Zorro:1.7999999999999998
Orange Crush:3.0
155 Belmont:17.5
1-900-FUK-MEUP:2.5
Vodka Russian:10.0
Danbooka:4.0
110 in the shade:17.5
Grand Blue:2.25
Baby Eskimo:12.0
Tennesee Mud:17.7
Swedish Coffee:9.26
Adam Sunrise:9.5
Absolut Stress #2:5.5
Chocolate Monkey:19.56
Texas Sling:3.0
A midsummernight dream:12.925
Zoksel:35.5
Fuzzy Asshole:4.15
Quick-sand:8.25
Snakebite and Black:17.0
Zimadori Zinger:13.5
Herbal flame:20.5
Jamaican Coffee:30.26
Mojito #3:8.88836
Apricot punch:356.0
B-52:0.91
Zambeer:11.74
Americano:2.0
Black Forest Shake:4.915
GG:9.99
Radler:24.0
Mudslinger:78.0
Campari Beer:25.45
Almond Chocolate Coffee:9.25
Amaretto Stone Sour #3:6.3
9 1/2 Weeks:3.53125
Absolutly Screwed Up:11.5
Whitecap Margarita:13.125
Bellini Martini:6.24
Jitterbug:12.6475
Moranguito:14.2
Amaretto Sweet & Sour:10.375
Rum Runner:13.0
H.D.:6.6
The Evil Blue Thing:3.0
Shark Attack:42.0
Jack's Vanilla Coke:14.205
Apple Grande:15.0
Bleeding Surgeon:37.8
Applejack:3.5
Adam Bomb:42.74
Arizona Antifreeze:0.99
Black and Brown:4.15
A Piece of Ass:8.24
Avalanche:15.0
Brandon and Will's Coke Float:11.5
Flaming Lamborghini:4.0
Zipperhead:15.0
A Gilligan's Island:8.0
Kioki Coffee:4.5
Apple Pie with A Crust:4.09375
Zorbatini:1.5
Vodka Fizz:6.59
Radioactive Long Island Iced Tea:8.0
Shot-gun:3.0
Bible Belt:5.1
Irish Curdling Cow:4.75
Sweet Tooth:10.0
Downshift:11.0
Pink Penocha:383.5
Orange Whip:12.24
Bruised Heart:2.0
Gideon's Green Dinosaur:10.5

A True Amaretto Sour:1.84
Kool First Aid:2.0625
Irish Russian:7.33125
Auburn Headbanger:2.0
Zima Blaster:15.0
Buccaneer:6.5
Homemade Kahlua:81.1
24k nightmare:2.0
Caribbean Boilermaker:28.5
Army special:20.15
Arizona Twister:15.865
Baby Guinness:3.0
Alice in Wonderland:10.5
501 Blue:7.0
Coke and Drops:3.3466899999999997
Ruby Tuesday:7.0625
Arctic Mouthwash:10.24
Brain Fart:224.2
Royal Bitch:2.0
Citrus Coke:3.0
Smut:4.49
Raspberry Cooler:6.24
Amaretto Sunset:18.65
Cherry Electric Lemonade:10.0
Girl From Ipanema:4.5
Ipamena:6.94
Dark Caipirinha:7.25
Jam Donut:1.145
Aviation:2.25
Dirty Martini:3.675
Duchamp's Punch:3.6025
Bacardi Cocktail:2.84375
Between The Sheets:4.0
Casino:2.425
Clover Club:3.65
Derby:1.9225
Mary Pickford:2.925
Monkey Gland:2.75
Paradise:14.0
Planter's Punch:4.5
Porto flip:14.0
Stinger:2.0
White Lady:2.6999999999999997
Bellini:7.0
Cosmopolitan:3.75
French 75:12.05
French Connection:2.25
Golden dream:7.0
Grasshopper:2.25
Hemingway Special:26.0
Horse's Neck:7.0625
Kir:6.0
Long Island Iced Tea:2.03125
Mimosa:3.0
Mint Julep:2.995
Pina Colada:5.25
Rose:2.2475
Barracuda:6.63125
Bramble:2.4
Dark and Stormy:4.5
Espresso Martini:1.83125
French Martini:2.25
Russian Spring Punch:2.25
Spritz:3.03125
Tommy's Margarita:2.55
Vampiro:4.09125
Vesper:2.475
Yellow Bird:2.25
Butter Baby:8.0
Boozy Snickers Milkshake:48.2
A1:8.42
Abbey Martini:14.09375
Absolutely Fabulous:13.5
Ace:12.7
Adam & Eve:10.92
Addington:18.5
Addison:10.5
Adios Amigos Cocktail:12.25
Gin Rickey:11.125
Salted Toffee Martini:2.91
Hunter's Moon:5.1
Zombie:4.38167
Bombay Cassis:10.3
Rosemary Blue:4.95
Empellón Cocina's Fat-Washed Mezcal:3.25
The Last Word:3.0
French Negroni:3.0
Pegu Club:3.0625
Corpse Reviver #2:3.03125
Boulevardier:3.25
Greyhound:4.5
Paloma:4.5
Bijou:3.03125
Gimlet:8.0
Martinez 2:3.1875
Oatmeal Cookie:9.5
Bahama Mama:11.0
Blue Hurricane:14.24
The Laverstoke:6.28
Brigadier:6.0
The Jimmy Conway:7.0
Old Pal:4.0
Tipperary:3.5
Penicillin:3.5
Corn n Oil:4.6425
A Furlong Too Late:6.0
A Night In Old Mandalay:6.5
A. J.:2.5
Abbey Cocktail:2.33125
Abilene:6.5
Acapulco:3.1174999999999997
Adam:3.125
Adonis Cocktail:2.28125
Affair:14.0
Affinity:3.5625
Slippery Nipple:2.0
Tequila Slammer:4.5
Spritz Veneziano:11.0
Espresso Rumtini:12.25
Brooklyn:3.64375
Broadside:5.5400100000000005
Bloody Punch:103.0
Halloween Punch:37.425
Gin Basil Smash:3.03
Munich Mule:10.6
Honney Bee:3.0
Bee's Knees:3.6
747 Drink:6.0
Aquamarine:4.0
Banana Cream Pi:10.0
Amaretto fizz:7.5
Spice 75:12.675

In [24]:
df

,Unnamed: 0,칵테일명,재료명,개수,단위,oz화개수,Category,재료비율
0,0,Mojito,Light Rum,2.5,oz,2.500,Rum,15.782828
1,1,Mojito,Juice Of Lime,2.5,half oz(juice),5.000,Ingredient,31.565657
2,2,Mojito,Sugar,2.0,tsp,0.250,Ingredient,1.578283
3,3,Mojito,Mint,3.0,NaN,0.090,Ingredient,0.568182
4,4,Mojito,Soda Water,1.0,cup,8.000,Ingredient,50.505051
...,...,...,...,...,...,...,...,...
2288,2288,Spice 75,Sugar,60.0,ml,1.800,Ingredient,14.201183
2289,2289,Spice 75,Allspice,1.0,tblsp,0.375,Ingredient,2.958580
2290,2290,Spice 75,Rum,20.0,cl,6.000,Rum,47.337278
2291,2291,Spice 75,Lime Juice,90.0,ml,2.700,Ingredient,21.301775
2292,2292,Spice 75,Champagne,6.0,cl,1.800,Champagne,14.201183

In [26]:
df.drop(["Unnamed: 0"],axis=1)

,칵테일명,재료명,개수,단위,oz화개수,Category,재료비율
0,Mojito,Light Rum,2.5,oz,2.500,Rum,15.782828
1,Mojito,Juice Of Lime,2.5,half oz(juice),5.000,Ingredient,31.565657
2,Mojito,Sugar,2.0,tsp,0.250,Ingredient,1.578283
3,Mojito,Mint,3.0,NaN,0.090,Ingredient,0.568182
4,Mojito,Soda Water,1.0,cup,8.000,Ingredient,50.505051
...,...,...,...,...,...,...,...
2288,Spice 75,Sugar,60.0,ml,1.800,Ingredient,14.201183
2289,Spice 75,Allspice,1.0,tblsp,0.375,Ingredient,2.958580
2290,Spice 75,Rum,20.0,cl,6.000,Rum,47.337278
2291,Spice 75,Lime Juice,90.0,ml,2.700,Ingredient,21.301775
2292,Spice 75,Champagne,6.0,cl,1.800,Champagne,14.201183

In [27]:
df.to_excel("new.xlsx")