## 1. 데이터 불러오기

In [1]:
import pandas as pd
import numpy as np

df = pd.read_excel('./fffffinal_5.xlsx')
df = df.drop(["Unnamed: 0"],axis=1)
df

,칵테일명,재료명,개수,단위,oz화개수,Category,재료비율,ABV,alcohol,alcohol_classification,ingrid_classification
0,Mojito,Light Rum,2.5,oz,2.500,Rum,15.782828,40.0,NaN,NaN,NaN
1,Mojito,Juice Of Lime,2.5,half oz(juice),5.000,Ingredient,31.565657,0.0,NaN,NaN,1.0
2,Mojito,Sugar,2.0,tsp,0.250,Ingredient,1.578283,0.0,NaN,NaN,NaN
3,Mojito,Mint,3.0,NaN,0.090,Ingredient,0.568182,0.0,NaN,NaN,NaN
4,Mojito,Soda Water,1.0,cup,8.000,Ingredient,50.505051,0.0,6.313131,1.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2288,Spice 75,Sugar,60.0,ml,1.800,Ingredient,14.201183,0.0,NaN,NaN,NaN
2289,Spice 75,Allspice,1.0,tblsp,0.375,Ingredient,2.958580,0.0,NaN,NaN,NaN
2290,Spice 75,Rum,20.0,cl,6.000,Rum,47.337278,40.0,NaN,NaN,NaN
2291,Spice 75,Lime Juice,90.0,ml,2.700,Ingredient,21.301775,0.0,NaN,NaN,1.0
2292,Spice 75,Champagne,6.0,cl,1.800,Champagne,14.201183,12.0,20.639053,2.0,NaN

## 2. EDA & Feature Engineering

In [2]:
import matplotlib.pyplot as plt
%matplotlib inline

import seaborn as sns
sns.set()

In [3]:
df['칵테일명'].count()

2293

In [4]:
cnt = 0
name = df['칵테일명'][cnt]
print(name)

Mojito

In [5]:
df['ingrid_classification']=""
df.head()

,칵테일명,재료명,개수,단위,oz화개수,Category,재료비율,ABV,alcohol,alcohol_classification,ingrid_classification
0,Mojito,Light Rum,2.5,oz,2.50,Rum,15.782828,40.0,NaN,NaN,
1,Mojito,Juice Of Lime,2.5,half oz(juice),5.00,Ingredient,31.565657,0.0,NaN,NaN,
2,Mojito,Sugar,2.0,tsp,0.25,Ingredient,1.578283,0.0,NaN,NaN,
3,Mojito,Mint,3.0,NaN,0.09,Ingredient,0.568182,0.0,NaN,NaN,
4,Mojito,Soda Water,1.0,cup,8.00,Ingredient,50.505051,0.0,6.313131,1.0,

In [6]:
while( cnt != df['칵테일명'].count()):
    while (df['칵테일명'][cnt] == name):
        if(df['Category'][cnt] =='Ingredient'):
            if(
                'Hot'in df['재료명'][cnt] or 
                'Boiling'in df['재료명'][cnt]
              ):
                df['ingrid_classification'][cnt] = 0
                cnt += 1
            elif(
                'Lemon'in df['재료명'][cnt] or 
                'lemon'in df['재료명'][cnt] or
                'Orange'in df['재료명'][cnt] or
                'Lime'in df['재료명'][cnt] or
                'Fresca'in df['재료명'][cnt]
              ):
                df['ingrid_classification'][cnt] = 1
                cnt += 1
            elif(
                'Grenadine'in df['재료명'][cnt] or 
                'Pinapple'in df['재료명'][cnt] or
                'Cranberr'in df['재료명'][cnt] or
                'Cherry'in df['재료명'][cnt] or
                'Apple'in df['재료명'][cnt] or
                'Peach'in df['재료명'][cnt] or
                'Banana'in df['재료명'][cnt] or
                'Grape'in df['재료명'][cnt] or
                'Coconut'in df['재료명'][cnt] or
                'Passion'in df['재료명'][cnt] or
                'Strawberr'in df['재료명'][cnt] or
                'Mango'in df['재료명'][cnt] or
                'Apricot'in df['재료명'][cnt] or
                'Berr'in df['재료명'][cnt] or
                'Blackberr'in df['재료명'][cnt] or
                'Cantaloupe'in df['재료명'][cnt] or
                'Guava'in df['재료명'][cnt] or
                'Kiwi'in df['재료명'][cnt] or
                'Papaya'in df['재료명'][cnt] or
                'Mint' in df['재료명'][cnt] or
                'Fruit' in df['재료명'][cnt] or
                'Blackcurrant' in df['재료명'][cnt] or
                'Raspberry'in df['재료명'][cnt]
              ):
                df['ingrid_classification'][cnt] = 2
                cnt += 1
            elif(
                'Nectar'in df['재료명'][cnt] or 
                'Agave'in df['재료명'][cnt] or
                'Caramel'in df['재료명'][cnt] or
                'Orgeat'in df['재료명'][cnt] or
                'Cinnamon'in df['재료명'][cnt] or
                'Hazlenut'in df['재료명'][cnt] or
                'Nutmeg'in df['재료명'][cnt] or
                'Sweetened'in df['재료명'][cnt] or
                'Almond'in df['재료명'][cnt] or
                'Cordial'in df['재료명'][cnt] or
                'Maple'in df['재료명'][cnt]
              ):
                df['ingrid_classification'][cnt] = 3
                cnt += 1
            elif(
                'Cream'in df['재료명'][cnt] or 
                'Milk'in df['재료명'][cnt] or
                'Coffee'in df['재료명'][cnt] or
                'Egg'in df['재료명'][cnt] or
                'Chocolate'in df['재료명'][cnt] or
                'Ice-cream'in df['재료명'][cnt] or
                'Yoghurt'in df['재료명'][cnt] or
                'Cocoa'in df['재료명'][cnt] or
                'Tomato'in df['재료명'][cnt] or
                'Espresso'in df['재료명'][cnt] or
                'Yolk'in df['재료명'][cnt] or
                'Vanila'in df['재료명'][cnt]
              ):
                df['ingrid_classification'][cnt] = 4
                cnt += 1
            elif(
                'Soda'in df['재료명'][cnt] or 
                'Coca-cola'in df['재료명'][cnt] or
                '7-up'in df['재료명'][cnt] or
                'Cider'in df['재료명'][cnt] or
                'Tonic'in df['재료명'][cnt] or
                'Sprite'in df['재료명'][cnt] or
                'Schweppes'in df['재료명'][cnt] or
                'Cola'in df['재료명'][cnt] or
                'Pepsi'in df['재료명'][cnt] or
                'Dr. Pepper'in df['재료명'][cnt] or
                'Carbonated'in df['재료명'][cnt]
              ):
                df['ingrid_classification'][cnt] = 6
                cnt += 1
            elif(
                'Ginger'in df['재료명'][cnt] or 
                'Cloves'in df['재료명'][cnt] or
                'Pepper'in df['재료명'][cnt] or
                'Allspice'in df['재료명'][cnt] or
                'Cardamom'in df['재료명'][cnt] or
                'Anis 'in df['재료명'][cnt]
              ):
                df['ingrid_classification'][cnt] = 5
                cnt += 1
            else:
                cnt += 1
        else:
            cnt+=1
        if(cnt == df['칵테일명'].count()):
            break
    if(cnt == df['칵테일명'].count()):
        break
    else:
        name = df['칵테일명'][cnt]

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:90: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:59: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:100: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [7]:
df

,칵테일명,재료명,개수,단위,oz화개수,Category,재료비율,ABV,alcohol,alcohol_classification,ingrid_classification
0,Mojito,Light Rum,2.5,oz,2.500,Rum,15.782828,40.0,NaN,NaN,
1,Mojito,Juice Of Lime,2.5,half oz(juice),5.000,Ingredient,31.565657,0.0,NaN,NaN,1
2,Mojito,Sugar,2.0,tsp,0.250,Ingredient,1.578283,0.0,NaN,NaN,
3,Mojito,Mint,3.0,NaN,0.090,Ingredient,0.568182,0.0,NaN,NaN,2
4,Mojito,Soda Water,1.0,cup,8.000,Ingredient,50.505051,0.0,6.313131,1.0,6
...,...,...,...,...,...,...,...,...,...,...,...
2288,Spice 75,Sugar,60.0,ml,1.800,Ingredient,14.201183,0.0,NaN,NaN,
2289,Spice 75,Allspice,1.0,tblsp,0.375,Ingredient,2.958580,0.0,NaN,NaN,5
2290,Spice 75,Rum,20.0,cl,6.000,Rum,47.337278,40.0,NaN,NaN,
2291,Spice 75,Lime Juice,90.0,ml,2.700,Ingredient,21.301775,0.0,NaN,NaN,1
2292,Spice 75,Champagne,6.0,cl,1.800,Champagne,14.201183,12.0,20.639053,2.0,

In [8]:
df.to_excel("plus_ingrid_2.xlsx")