## 1. 데이터 불러오기

In [1]:
import pandas as pd
import numpy as np

df = pd.read_excel('./plus_ingrid_2.xlsx')
df = df.drop(["Unnamed: 0"],axis=1)
df

,칵테일명,재료명,개수,단위,oz화개수,Category,재료비율,ABV,alcohol,alcohol_classification,ingrid_classification
0,Mojito,Light Rum,2.5,oz,2.500,Rum,15.782828,40.0,NaN,NaN,NaN
1,Mojito,Juice Of Lime,2.5,half oz(juice),5.000,Ingredient,31.565657,0.0,NaN,NaN,1.0
2,Mojito,Sugar,2.0,tsp,0.250,Ingredient,1.578283,0.0,NaN,NaN,NaN
3,Mojito,Mint,3.0,NaN,0.090,Ingredient,0.568182,0.0,NaN,NaN,2.0
4,Mojito,Soda Water,1.0,cup,8.000,Ingredient,50.505051,0.0,6.313131,1.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...
2288,Spice 75,Sugar,60.0,ml,1.800,Ingredient,14.201183,0.0,NaN,NaN,NaN
2289,Spice 75,Allspice,1.0,tblsp,0.375,Ingredient,2.958580,0.0,NaN,NaN,5.0
2290,Spice 75,Rum,20.0,cl,6.000,Rum,47.337278,40.0,NaN,NaN,NaN
2291,Spice 75,Lime Juice,90.0,ml,2.700,Ingredient,21.301775,0.0,NaN,NaN,1.0
2292,Spice 75,Champagne,6.0,cl,1.800,Champagne,14.201183,12.0,20.639053,2.0,NaN

## 2. EDA & Feature Engineering

In [2]:
import matplotlib.pyplot as plt
%matplotlib inline

import seaborn as sns
sns.set()

In [3]:
df['칵테일명'].count()

2293

In [4]:
cnt = 0
name = df['칵테일명'][cnt]
print(name)

Mojito

In [5]:
df.head()

,칵테일명,재료명,개수,단위,oz화개수,Category,재료비율,ABV,alcohol,alcohol_classification,ingrid_classification
0,Mojito,Light Rum,2.5,oz,2.50,Rum,15.782828,40.0,NaN,NaN,NaN
1,Mojito,Juice Of Lime,2.5,half oz(juice),5.00,Ingredient,31.565657,0.0,NaN,NaN,1.0
2,Mojito,Sugar,2.0,tsp,0.25,Ingredient,1.578283,0.0,NaN,NaN,NaN
3,Mojito,Mint,3.0,NaN,0.09,Ingredient,0.568182,0.0,NaN,NaN,2.0
4,Mojito,Soda Water,1.0,cup,8.00,Ingredient,50.505051,0.0,6.313131,1.0,6.0

In [6]:
while( cnt != df['칵테일명'].count()):
    while (df['칵테일명'][cnt] == name):
        if(df['Category'][cnt] =='Liqueur'):
            if(
                'Dry Vermouth'in df['재료명'][cnt] or 
                'Red Sweet Vermouth'in df['재료명'][cnt] or
                'Grand Marnier'in df['재료명'][cnt] or
                'Zima'in df['재료명'][cnt] or
                'Orange Bitters'in df['재료명'][cnt] or
                'Blue Curacao'in df['재료명'][cnt] or
                'Curacao'in df['재료명'][cnt] or
                'Orange Curacao'in df['재료명'][cnt] or
                'Cointreau'in df['재료명'][cnt]
              ):
                df['ingrid_classification'][cnt] = 1
                cnt += 1
            elif(
                'Maraschino'in df['재료명'][cnt] or 
                'Sloe Gin'in df['재료명'][cnt] or
                'Passoa'in df['재료명'][cnt] or
                'Pernod'in df['재료명'][cnt] or
                'St.Germain'in df['재료명'][cnt] or
                'Creme De Banane'in df['재료명'][cnt] or
                'Blue Maui'in df['재료명'][cnt] or
                'Creme De Mure'in df['재료명'][cnt] or
                'Applejack'in df['재료명'][cnt] or
                'Peach Bitters'in df['재료명'][cnt] or
                'Kirschwasser'in df['재료명'][cnt] or
                'Pisang Ambon'in df['재료명'][cnt]
              ):
                df['ingrid_classification'][cnt] = 2
                cnt += 1
            elif(
                'Rosso Vermouth'in df['재료명'][cnt] or 
                'Sweet Vermouth'in df['재료명'][cnt] or
                'Vermouth'in df['재료명'][cnt] or
                'Hpnotiq'in df['재료명'][cnt] or
                'Amaretto'in df['재료명'][cnt] or
                'Green Chartreuse'in df['재료명'][cnt] or
                'Yellow Chartreuse'in df['재료명'][cnt] or
                'Creme De Cassis'in df['재료명'][cnt] or
                'Dark Creme De Cacao'in df['재료명'][cnt] or
                'Green Creme De Menthe'in df['재료명'][cnt] or
                'Rumple Minze 'in df['재료명'][cnt] or
                'White Creme De Cacao'in df['재료명'][cnt] or
                'White Creme de Menthe'in df['재료명'][cnt] or
                'Kummel'in df['재료명'][cnt] or
                'Hot Damn'in df['재료명'][cnt] or
                'Chopped Bittersweet Or Semi-Sweet Chocolate'in df['재료명'][cnt] or
                'Yukon Jack'in df['재료명'][cnt] or
                'Benedictine'in df['재료명'][cnt] or
                'Galliano'in df['재료명'][cnt] or
                'Sarsaparilla'in df['재료명'][cnt] or
                'Drambuie'in df['재료명'][cnt] or
                'Baileys'in df['재료명'][cnt] or
                'Anisette'in df['재료명'][cnt] or
                'Ouzo'in df['재료명'][cnt] or
                'Jagermeister'in df['재료명'][cnt] or
                'Goldschlager'in df['재료명'][cnt] or
                'Frangelic'in df['재료명'][cnt] or
                'Creme De Cacao'in df['재료명'][cnt]
              ):
                df['ingrid_classification'][cnt] = 3
                cnt += 1
            elif(
                'Kahlua'in df['재료명'][cnt] or 
                'Tia maria'in df['재료명'][cnt] or
                'Advocaat'in df['재료명'][cnt]
              ):
                df['ingrid_classification'][cnt] = 4
                cnt += 1
            elif(
                'Campari'in df['재료명'][cnt] or 
                'Green Chartreuse'in df['재료명'][cnt] or
                'Absinthe'in df['재료명'][cnt] or
                'Angostura Bitters'in df['재료명'][cnt] or
                'Bitters'in df['재료명'][cnt] or
                'Peychaud Bitters'in df['재료명'][cnt] or
                'Aquavit'in df['재료명'][cnt] or
                'Cachaca'in df['재료명'][cnt] or
                'Ricard'in df['재료명'][cnt] or
                'Sambuca'in df['재료명'][cnt] or
                'Aperol'in df['재료명'][cnt] or
                'Grain Alcohol'in df['재료명'][cnt] or
                'Everclear 'in df['재료명'][cnt]
              ):
                df['ingrid_classification'][cnt] = 5
                cnt += 1
            else:
                cnt += 1
        else:
            cnt+=1
        if(cnt == df['칵테일명'].count()):
            break
    if(cnt == df['칵테일명'].count()):
        break
    else:
        name = df['칵테일명'][cnt]

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:87: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:70: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [7]:
df

,칵테일명,재료명,개수,단위,oz화개수,Category,재료비율,ABV,alcohol,alcohol_classification,ingrid_classification
0,Mojito,Light Rum,2.5,oz,2.500,Rum,15.782828,40.0,NaN,NaN,NaN
1,Mojito,Juice Of Lime,2.5,half oz(juice),5.000,Ingredient,31.565657,0.0,NaN,NaN,1.0
2,Mojito,Sugar,2.0,tsp,0.250,Ingredient,1.578283,0.0,NaN,NaN,NaN
3,Mojito,Mint,3.0,NaN,0.090,Ingredient,0.568182,0.0,NaN,NaN,2.0
4,Mojito,Soda Water,1.0,cup,8.000,Ingredient,50.505051,0.0,6.313131,1.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...
2288,Spice 75,Sugar,60.0,ml,1.800,Ingredient,14.201183,0.0,NaN,NaN,NaN
2289,Spice 75,Allspice,1.0,tblsp,0.375,Ingredient,2.958580,0.0,NaN,NaN,5.0
2290,Spice 75,Rum,20.0,cl,6.000,Rum,47.337278,40.0,NaN,NaN,NaN
2291,Spice 75,Lime Juice,90.0,ml,2.700,Ingredient,21.301775,0.0,NaN,NaN,1.0
2292,Spice 75,Champagne,6.0,cl,1.800,Champagne,14.201183,12.0,20.639053,2.0,NaN

In [8]:
df.to_excel("ingrid_liqueur_classify_final.xlsx")